### ISSUE TITLE
Missing citations for related work

### ISSUE THREAD

**Issue by jnhwkim** [kaistAI/prometheus-vision#2]
I have noticed that certain citations for the related work section are absent in the paper, so I leave the paper information that comes to my mind (without shame, including ours..).

* LLMScore: Unveiling the Power of Large Language Models in Text-to-Image Synthesis Evaluation (NeurIPS 2023) https://arxiv.org/abs/2305.11116
* SelfEval: Leveraging the discriminative nature of generative models for evaluation (arXiv 2023) https://arxiv.org/abs/2311.10708
* Mutual Information Divergence: A Unified Metric for Multimodal Generative Models (NeurIPS 2022) http://arxiv.org/abs/2205.13445

**Comment by SeungoneKim** [comment]
@jnhwkim Thanks for pointing out! We'll update these papers in our draft:)
